# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce7e0c7b3e999873ea93aba1f04ec650c29ff0463e29e3355f2c15232ebf5daebfe49f23c942eecc1baeac5870ad85d3f38c4944e4bd00879c800c056753477

test:
  secret_key_base: 6c6e06bdb1b7533077819565cb6fb82d83ca40c4a27d89afae2e557b34ea97201dd3e9765d4ad6da65873b0308e65d4a12a70942a7a869fe00a204cdee1c93dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
